# Generated by Django 4.2.9 on 2024-10-24 10:12

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('student', 'student'), ('teacher', 'teacher')], default='student', max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm cập nhật')),
                ('answer_text', models.CharField(max_length=255, verbose_name='Câu trả lời')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Câu trả lời đúng')),
            ],
            options={
                'verbose_name': 'QL Đáp án',
                'verbose_name_plural': 'QL Đáp án',
                'db_table': 'answers',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm cập nhật')),
                ('title', models.CharField(max_length=255, verbose_name='Tên bài kiểm tra')),
                ('room_name', models.CharField(max_length=255, verbose_name='Tên phòng thi')),
                ('start_time', models.DateTimeField(verbose_name='Thời gian bắt đầu')),
                ('finish_time', models.DateTimeField(verbose_name='Thời gian kết thúc')),
                ('time_todo', models.IntegerField(default=15, verbose_name='Thời gian làm bài (phút)')),
                ('room_code', models.CharField(max_length=15, unique=True, verbose_name='Mã phòng thi')),
                ('created_by', models.CharField(max_length=255, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'QL Bài kiểm tra',
                'verbose_name_plural': 'QL Bài kiểm tra',
                'db_table': 'exams',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm cập nhật')),
                ('question_text', models.CharField(max_length=255, verbose_name='Câu hỏi')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.exam', verbose_name='Bài kiểm tra')),
            ],
            options={
                'verbose_name': 'QL Câu hỏi',
                'verbose_name_plural': 'QL Câu hỏi',
                'db_table': 'questions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm cập nhật')),
                ('score', models.IntegerField(default=0, verbose_name='Điểm số')),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.exam', verbose_name='Bài thi')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
            ],
            options={
                'verbose_name': 'Kết quả thi',
                'verbose_name_plural': 'Kết quả thi',
                'db_table': 'results',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ResultDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm cập nhật')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Kết quả (Đ/S)')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.answer', verbose_name='Đáp án lựa chọn')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.question', verbose_name='Câu hỏi')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.result', verbose_name='Bài kiểm tra')),
            ],
            options={
                'verbose_name': 'Kết quả câu hỏi',
                'verbose_name_plural': 'Kết quả câu hỏi',
                'db_table': 'result_details',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question', verbose_name='Câu hỏi'),
        ),
    ]
