# Generated by Django 4.2.9 on 2024-11-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_result_is_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTrueFalse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm cập nhật')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='monitor',
            options={'ordering': ('-created_at',), 'verbose_name': 'Video giám sát', 'verbose_name_plural': 'Video giám sát'},
        ),
        migrations.AddField(
            model_name='monitor',
            name='reason',
            field=models.CharField(default='', max_length=255, verbose_name='Lý do phát hiện gian lận'),
        ),
        migrations.AddField(
            model_name='result',
            name='reason',
            field=models.CharField(default='', max_length=255, verbose_name='Lý do phát hiện gian lận'),
        ),
        migrations.AlterModelTable(
            name='monitor',
            table='monitors',
        ),
    ]
