# Generated by Django 4.2.9 on 2024-11-03 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_questiontruefalse_alter_monitor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questiontruefalse',
            options={'ordering': ('-created_at',), 'verbose_name': 'Câu hỏi đúng sai', 'verbose_name_plural': 'Câu hỏi đúng sai'},
        ),
        migrations.AddField(
            model_name='questiontruefalse',
            name='answer',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='true', max_length=7, verbose_name='Đáp án'),
        ),
        migrations.AddField(
            model_name='questiontruefalse',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.exam', verbose_name='Bài kiểm tra'),
        ),
        migrations.AddField(
            model_name='questiontruefalse',
            name='question_text',
            field=models.CharField(default='', max_length=255, verbose_name='Câu hỏi'),
        ),
        migrations.AlterField(
            model_name='questiontruefalse',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='questiontruefalse',
            table='question_tf',
        ),
        migrations.CreateModel(
            name='QuestionFill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm cập nhật')),
                ('question_text', models.CharField(default='', max_length=255, verbose_name='Câu hỏi')),
                ('answer', models.CharField(default='', max_length=255, verbose_name='Đáp án đúng')),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.exam', verbose_name='Bài kiểm tra')),
            ],
            options={
                'verbose_name': 'Câu hỏi điền đáp án',
                'verbose_name_plural': 'Câu hỏi điền đáp án',
                'db_table': 'question_fill',
                'ordering': ('-created_at',),
            },
        ),
    ]
