# Generated by Django 4.2.9 on 2024-11-03 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_questiontruefalse_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultTrueFalse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm cập nhật')),
                ('answer', models.CharField(default='', max_length=7, verbose_name='Đáp án chọn')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Kết quả (Đ/S)')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.questiontruefalse', verbose_name='Câu hỏi')),
                ('result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.result', verbose_name='Bài kiểm tra')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResultFill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm cập nhật')),
                ('answer', models.CharField(default='', max_length=255, verbose_name='Câu trả lời')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Kết quả (Đ/S)')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.questionfill', verbose_name='Câu hỏi')),
                ('result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.result', verbose_name='Bài kiểm tra')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
