# Generated by Django 4.2.9 on 2024-11-05 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_resulttruefalse_resultfill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontruefalse',
            name='answer',
        ),
        migrations.CreateModel(
            name='AnswerTrueFalse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm cập nhật')),
                ('clause', models.CharField(default='', max_length=255, verbose_name='Mệnh đề')),
                ('answer', models.CharField(choices=[('true', 'true'), ('false', 'false')], default='true', max_length=7, verbose_name='Đáp án')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.questiontruefalse', verbose_name='Câu hỏi')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
